### ISSUE TITLE
Workflow isn't working.

### ISSUE THREAD

**Issue by ricardofeynman** [RenderRift/ComfyUI-RenderRiftNodes#1]
This seems cool. Thanks for releasing. 

Just tried to test the workflow after last update and the json doesn't load for me.

Looking forward to the second workflow.json for Workflow 2: Video Comparison Setup.

**Comment by RenderRift** [comment]
No probs! Does anything load at all or do you have any errors that you can share? 

Thanks

**Comment by ricardofeynman** [comment]
At this stage I'm guessing it's something in my setup. It seems to be an especially buggy week in ComfyUI-land. 

Many workflows (both json and embedded image) downloaded from github are causing issues over the last couple days. Now just need to go create an issue over on ComfyUI-VideoHelperSuite repo so I can test out Workflow 2!

**Comment by RenderRift** [comment]
It could be my setup as I grouped one of my nodes with VHS's nodes which may not have come through right if you don't have that plugin install (I though it would just pop up as a missing node to install). 

I've attached the workflow without any groups, let me know how you get on. 
[workflow-comparison-nogroups.json](https://github.com/RenderRift/ComfyUI-RenderRiftNodes/files/13798051/workflow-comparison-nogroups.json)
Thanks

**Comment by ricardofeynman** [comment]
I've been having a variety of issues with VHS for three days, across many workflows.

The workflow you linked loaded first time, groups were not the cause in my case.
